
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  # ----------- SERVER ----------------
  config.vm.define "kelmoutoS" do |server|
    server.vm.hostname = "kelmoutoS"
    server.vm.network "private_network", ip: "192.168.56.110"

    server.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
    end

    # Install K3s server + kubectl
    server.vm.provision "file", source: "./deployment.yaml", destination: "/tmp/deployment.yaml"
    server.vm.provision "file", source: "./service.yaml", destination: "/tmp/service.yaml"
    server.vm.provision "file", source: "./ingress.yaml", destination: "/tmp/ingress.yaml"

    server.vm.provision "shell", path: "./scripts/script.sh" 
  end
end
