# | Concept             | Meaning                                         |
# | ------------------- | ----------------------------------------------- |
# | **Box**             | A reusable VM image (e.g., Ubuntu)              |
# | **Provisioning**    | Installing software automatically               |
# | **Provider**        | The virtualization system (VirtualBox, VMware…) |
# | **Private Network** | VM gets a static IP                             |
# | **Forwarded ports** | Mapping ports from host → VM                    |
# | **Synced folder**   | Share files between host ↔ VM                   |

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  # ----------- SERVER ----------------
  config.vm.define "kelmoutoS" do |server|
    # server is the configuration object for THIS machine only.
    server.vm.hostname = "kelmoutoS"
    server.vm.network "private_network", ip: "192.168.56.110"
    # Creates a network interface visible only inside your computer.

    # Assigns VM a static IP.

    #  Required so the worker can reach the server.
    server.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
    end

    # Install K3s server + kubectl
    server.vm.provision "file", source: "./deployment.yaml", destination: "/tmp/deployment.yaml"
    server.vm.provision "file", source: "./service.yaml", destination: "/tmp/service.yaml"
    server.vm.provision "file", source: "./ingress.yaml", destination: "/tmp/ingress.yaml"

    server.vm.provision "shell", inline: <<-SHELL
      set -e
      curl -sfL https://get.k3s.io | sh -
      until sudo kubectl get node 2>/dev/null; do
        echo "waiting for k3s to start..."
        sleep 3
      done
      sudo kubectl apply -f /tmp/deployment.yaml
      sudo kubectl apply -f /tmp/service.yaml
      sudo kubectl apply -f /tmp/ingress.yaml
      echo "waiting for the app to start..."
      sudo kubectl wait --for=condition=ready pod --all --timeout=300s
      if [ $? -eq "0" ];then
        echo "the app started successfully."
      else
        echo "something went wrong with the app"
      fi
      echo "alias k='kubectl'" >> /home/vagrant/.bashrc
      chown vagrant:vagrant /home/vagrant/.bashrc
      sudo chmod 777 /etc/rancher/k3s/k3s.yaml
    SHELL
  end
end
