
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  # ----------- SERVER ----------------
  config.vm.define "kelmoutoS" do |server|
  
    server.vm.hostname = "kelmoutoS"
    server.vm.network "private_network", ip: "192.168.56.110"

    server.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
    end

    # Install K3s server + kubectl
    server.vm.provision "shell", path: "./scripts/install_k3s_server.sh"
  end


  # ----------- WORKER ----------------
  config.vm.define "kelmoutoSW" do |worker|
    worker.vm.hostname = "kelmoutoSW"
    worker.vm.network "private_network", ip: "192.168.56.111"

    worker.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
    end

    # Install K3s agent
    worker.vm.provision "shell", path: "./scripts/install_k3s_agent.sh"
  end

end
